global:
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  defaultStorageClass: "local-path"
  redis:
    password: "yourpassword"

image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: 7.4.0-debian-12-r4
  debug: false

## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
##
architecture: replication

commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  # databases 32

master:
  ## @param master.count Number of Redis&reg; master instances to deploy (experimental, requires additional configuration)
  ##
  count: 1
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  resources:
    limits:
      cpu: "1"
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 300Mi

  persistence:
    ## @param master.persistence.enabled Enable persistence on Redis&reg; master nodes using Persistent Volume Claims
    ##
    enabled: true
    ## @param master.persistence.size Persistent Volume size
    ##
    size: 8Gi


replica:
  replicaCount: 1
  disableCommands:
    - FLUSHDB
    - FLUSHALL

  resources:
    limits:
      cpu: "1"
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 300Mi

  persistence:
    ## @param replica.persistence.enabled Enable persistence on Redis&reg; replicas nodes using Persistent Volume Claims
    ##
    enabled: true
    size: 8Gi





